#device:
device: cpu

# data:
data_dir: data/  # path to the unzipped dataset directories(H36m/AMASS/3DPW)
dataset: h36m  # amass_3d

input_n: 10  # number of model's input frames. 25 fps
output_n: 25  # number of model's output frames. 25 fps

# model:
model: seq2seq
hidden_size: 256 # 1024

# run:
mode: train  # choices=['train','test','viz']
optimizer: adam
seed: 42
n_epochs: 5  # number of epochs to train
batch_size: 16  # batch size
lr: 0.005  # Learning rate of the optimizer
weight_decay: 0.00001