#device:
device: cpu

#experiment:
experiment_name: load_weights_deneme

# data:
data_dir: ../data  # path to the unzipped dataset directories
dataset: amazon-polarity # kaggle-insults or amazon-polarity
max_sentence_length : 120
load_vocabulary: True # load dataset-specific vocabulary

# label:
out_dim: 1  # 1 if binary

# model:
model: DeepmojiNet
lsmt_hidden_size: 512

# embeddings:
train_embeddings: False
embedding_size: 300
embedding_type: 'spacy'
load_embeddings: True # load preprocessed embedding matrix

# run:
optimizer: adam
seed: 42
n_epochs: 2  # number of epochs to train
batch_size: 128  # batch size
learning_rate: 0.001  # Learning rate of the optimizer
weight_decay: None