#device:
device: cpu  # {gpu | cpu}

#experiment:
experiment_name: deepmoji_base_deneme  # format: {deepmoji|_transfer}_{base|pretraining}_{freeze}_{lstm}_{classifier_head_arch}
                              # -> deepmoji_base_lstm512_cls128_128_1 (plain deepmoji on kaggle-insult)
                              # -> deepmoji_pretraining_lstm512_cls128_128_1 (plain deepmoji on amazon-polarity)
                              # -> deepmoji_transfer_freezeTrue_lstm512_cls128_128_1 (deepmoji classifier on kaggle-insult)
# data:
data_dir: ../data
dataset: kaggle-insults # {kaggle-insults | amazon-polarity}
max_sentence_length : 100  # kaggle-insults:{100}, amazon-polarity:{120}
preprocess_type: gensim_processed  # kaggle-insults:{only_tokenized | spacy_processed | gensim_processed}, amazon-polarity:{gensim_processed}

# label:
out_dim: 1  # binary

# model:
model: DeepmojiBasedClassifier # {DeepmojiNet | DeepmojiBasedClassifier}
lsmt_hidden_size: 512
freeze_base: False  # {True | False} only for DeepmojiBasedClassifier
pretraining_experiment_name: pretraining_hidden512  # only for DeepmojiBasedClassifier

# embeddings:
load_vocabulary: False  # load dataset-specific vocabulary from disk. kaggle-insults:{False}, amazon-polarity:{True}
load_embeddings: False  # load dataset-specific embeddings from disk. kaggle-insults:{False}, amazon-polarity:{True}
train_embeddings: False
embedding_size: 300
embedding_type: 'spacy'  # {spacy}

# run:
optimizer: adam  # {adam | rmsprop}
seed: 42
n_epochs: 50
batch_size: 64
learning_rate: 0.0001