#device:
device: cpu  # {gpu | cpu}

#experiment:
experiment_name: bert_freeze_True_128  # format: bert_{freeze}_{classifier_head_arch}_{preprocess_type} # -> bert_freezeTrue_cls128_1

# data:
data_dir: ../data
dataset: kaggle-insults  # {kaggle-insults | amazon-polarity}
max_sentence_length : 100  # kaggle-insults:{100}, amazon-polarity:{120}
preprocess_type: gensim_processed  # kaggle-insults:{only_tokenized | spacy_processed | gensim_processed}, amazon-polarity:{gensim_processed}

# label:
out_dim: 1  # binary

# model:
model: BertBasedClassifier
freeze_base: True # {True | False}

# run:
optimizer: adam # {adam | rmsprop}
seed: 42
n_epochs: 30
batch_size: 64
learning_rate: 0.00005 # suggested 1e-5 - 5e-5