#device:
device: cpu

# data:
data_dir: ../data  # path to the unzipped dataset directories
dataset: kaggle-insults  # kaggle-insults

# label:
out_dim: 1  # 1 if binary

# model:
model: DeepmojiNet
lsmt_hidden_size: 512

# embeddings:
train_embeddings: False
embedding_size: 300
embedding_type: 'spacy'

# run:
optimizer: adam
seed: 42
n_epochs: 5  # number of epochs to train
batch_size: 16  # batch size
lr: 0.005  # Learning rate of the optimizer
weight_decay: 0.00001