#device:
device: cpu

#experiment:
experiment_name: bert_deneme

# data:
data_dir: ../data  # path to the unzipped dataset directories
dataset: kaggle-insults # kaggle-insults or amazon-polarity
max_sentence_length : 100
load_vocabulary: False # load dataset-specific vocabulary
pretraining_experiment_name: pretraining_hidden512  # relevant when DeepmojiBasedClassifier

# label:
out_dim: 1  # 1 if binary

# model:
model: BertBasedClassifier # DeepmojiNet or DeepmojiBasedClassifier or BertBasedClassifier
lsmt_hidden_size: 512  # relevant when DeepmojiNet

# embeddings:
train_embeddings: False
embedding_size: 300
embedding_type: 'spacy'
load_embeddings: True # load preprocessed embedding matrix

# run:
optimizer: adam
seed: 42
n_epochs: 20  # number of epochs to train
batch_size: 64  # batch size
learning_rate: 0.00005  # Learning rate of the optimizer
weight_decay: None