#device:
device: cpu

#experiment:
experiment_name: colab_ready

# data:
data_dir: ../data  # path to the unzipped dataset directories
dataset: kaggle-insults  # kaggle-insults
max_sentence_length : 100

# label:
out_dim: 1  # 1 if binary

# model:
model: DeepmojiNet
lsmt_hidden_size: 256

# embeddings:
train_embeddings: False
embedding_size: 300
embedding_type: 'spacy'

# run:
optimizer: adam
seed: 42
n_epochs: 2  # number of epochs to train
batch_size: 32  # batch size
learning_rate: 0.001  # Learning rate of the optimizer
weight_decay: None